In [9]:
import numpy as np

In [10]:
Arr = np.random.randint(1,101, size=(10,5))

In [11]:
Arr

array([[ 86,  78,  51,  47,  22],
       [ 39,  39,  29,  80,  47],
       [ 34,  86,  38,  24,  29],
       [ 65,  82,   4,  52,  19],
       [ 94,   4,  25,  22,  34],
       [  8,  68,  55,  89,  32],
       [ 25,  36,  58,  80,  25],
       [ 63,  11,  83,  98,  62],
       [ 44, 100,   2,  72,  19],
       [ 89, 100,  25,  94,  26]])

In [12]:
new_Arr = Arr[0:3, 0:2]

In [13]:
new_Arr

array([[86, 78],
       [39, 39],
       [34, 86]])

In [14]:
Arr[0:3,0:2]=0

In [15]:
Arr

array([[  0,   0,  51,  47,  22],
       [  0,   0,  29,  80,  47],
       [  0,   0,  38,  24,  29],
       [ 65,  82,   4,  52,  19],
       [ 94,   4,  25,  22,  34],
       [  8,  68,  55,  89,  32],
       [ 25,  36,  58,  80,  25],
       [ 63,  11,  83,  98,  62],
       [ 44, 100,   2,  72,  19],
       [ 89, 100,  25,  94,  26]])